display_name: Classipod
icon: snap/gui/classipod.png

keywords:
  - Music
  - Audio
  - iPod
  - Local
  - Songs
  - Offline
  - Subsonic
  - Navidrome
  - Streaming

generic_name: Music Player
categories:
  - Music

startup_notify: true