enum SharedPreferencesKeys {
  languageLocaleCode,
  deviceColor,
  clickWheelSize,
  isTouchScreenEnabled,
  repeatMode,
  vibrate,
  clickWheelSound,
  volumeMode,
  splitScreenEnabled,
  immersiveMode,
  isMenuFirstTime,
  isNowPlayingFirstTime,
  isSearchFirstTime,
}
